### ISSUE TITLE
Enabling profiling introduces RejectedExecutionExceptions in application

### ISSUE THREAD

**Issue by oli-d-ovo** [GoogleCloudPlatform/cloud-profiler-java#30] opened 2020-07-28 12:41 UTC
I am trying to enable Stackdriver profiling on one of my Clojure services, following the guide at https://cloud.google.com/profiler/docs/profiling-java in order to enable profiling, and since enabling I have started to see the following exception being thrown:

`java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@3d5c117a[Not completed, task = clojure.core$binding_conveyor_fn$fn__5754@59ea0e16] rejected from java.util.concurrent.ThreadPoolExecutor@68f158bb[Shutting down, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 2769]`

I've identified that I can reliably reproduce the exception if I shut down the service (by killing the Kubernetes pods) while the service is processing messages from Pub/Sub. 

It seems that the following line is introducing the error into our system (a JVM argument in a Dockerfile):

"-agentpath:/opt/cprof/profiler_java_agent.so=-cprof_service=flow-redeemer-clj,-cprof_enable_heap_sampling,-logtostderr"

The Dockerfile looks like:

```
FROM openjdk:11

ADD ./target/uberjar/flow-redeemer.jar /flow-redeemer.jar

RUN mkdir -p /opt/cprof && \
  wget -q -O- https://storage.googleapis.com/cloud-profiler/java/latest/profiler_java_agent.tar.gz \
  | tar xzv -C /opt/cprof

CMD [ "java", \
      "-Dclojure.spec.check-asserts=true", \
      "-Dcom.sun.management.jmxremote", \
      "-Dcom.sun.management.jmxremote.authenticate=false", \
      "-Dcom.sun.management.jmxremote.ssl=false", \
      "-Dcom.sun.management.jmxremote.local.only=false", \
      "-Dcom.sun.management.jmxremote.port=9999", \
      "-Dcom.sun.management.jmxremote.rmi.port=9999", \
      "-Djava.rmi.server.hostname=127.0.0.1", \
      "-XX:MaxRAMPercentage=90", \
      "-agentpath:/opt/cprof/profiler_java_agent.so=-cprof_service=flow-redeemer-clj,-cprof_enable_heap_sampling,-logtostderr", \
      "-jar", "/flow-redeemer.jar" ]
```

I've confirmed that removing the line quoted above stops the exception from being thrown.

It appears that the RejectedExecutionException is thrown when `execute` is called on the ThreadPoolExecutor after it has been shut down. However, I haven't come across this issue while profiling is disabled.

Does anyone know if enabling profiling introduces any unusual behaviour when working with multiple threads?

**Comment by kalyanac** [comment] 2020-07-29 03:23
Thanks for reporting this.

How many instances/tasks of each service have Profiler agent enabled? If it is more than 1, do you see these messages on all of the instances? 

Since you mentioned that you can reproduce this by killing the pods while they are processing messages, do you see any interruptions in your service health when Profiler agent is active? Do they continue to be healthy when Profiler is enabled?

If you have not tried with more than one instance active, can you try and let us know your observations?

**Comment by nolanmar511** [comment] 2022-09-15 20:53
Closing due to no follow-up.

**Closed by nolanmar511** 2022-09-15 20:53 UTC
